{application,kv,
             [{applications,[kernel,stdlib,elixir,logger]},
              {description,"kv"},
              {modules,['Elixir.KV','Elixir.KV.Bucket','Elixir.KV.Registry',
                        'Elixir.KV.Router','Elixir.KV.Supervisor']},
              {registered,[]},
              {vsn,"0.1.0"},
              {env,[{routing_table,[]}]},
              {mod,{'Elixir.KV',[]}}]}.
